name: typecheck

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Typecheck
        run: bun typecheck
